# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BrainChildRalph
author: 
  name: branchildralph
  twitter: 
  github: branchildralph
description: >- # this means to ignore newlines until "baseurl:"
  BrainChildRalph's Blog for research and development notes. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brainchildralph.github.io"

#logo:
#  path: "/img/favicons/android-chrome-192x192.png"
#  width: 192
#  height: 192

analytics:
  google: UA-111464944-2

adsense:
  ad-client: ca-pub-3071174904319274

comments:
  disqus: enhanceralph

# Build settings
paginate: 10 # the number of post per page
#paginate_multiple:
#  - paginate: 10
#    paginate_path: '/web/page:num/'
#    sub_dir: '/web'
#  - paginate: 10
#    paginate_path: '/page:num/'
#    sub_dir: '/'

highlighter: rouge
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed # Possible values -> nested / expanded / compact / compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Handling Reading
exclude:
  - "README.md"
  - "LICENSE"
